# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:      pretty
baseurl: 	    	/books2read/
url:            http://qiyanjun.github.io/

# Setup
title:            	"Books To Read"
tagline:          	"books2read"
description:        "A List of Helpful Books for Computer Science Graduate to Read:"
future: 			true

author:
  name:           'Yanjun Qi'
  url:            https://twitter.com/Qdatalab
